config/routes.rb
QnaForum::Application.routes.draw do

  get "contact/index"
  post "contact/send_mail"

  devise_for :users

  root :to => "questions#index"
  
  resources :questions do
    collection do
       get 'rank_me'
       get 'update_new_answer'
     end
     resources :answers
  end

end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers ,:dependent => :destroy
  has_many :ranks, :as => :rankable
  belongs_to :user
  attr_accessible :question,:header
  validates :question, :presence => true
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  # GET /questions
  # GET /questions.json
  before_filter :authenticate_user!, :except => [:show,:index,:update_new_answer]
  before_filter :load_basics
  before_filter :check_if_owner, :only => [ :edit ,:update, :delete]
  def index  
    @questions = Question.order('created_at desc').paginate(:page => params[:page], :per_page => 8)
    @rescent_answers = Answer.order('created_at desc').limit(6)
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @question = Question.find(params[:id])
    @answers = @question.answers.order('rank desc')
    @answer = @question.answers.build
  end

  # GET /questions/new
  # GET /questions/new.json
  def new
    @question = Question.new
  end

  def edit
    @question ||= Question.find(params[:id])
  end

  def create
    @question = current_user.questions.new(params[:question])

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully posted.' }
        format.json { render json: @question, status: :created, location: @question }
      else
        format.html { render action: "new" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def update
    @question ||= Question.find(params[:id])

    respond_to do |format|
      if @question.update_attributes(params[:question])
        format.html { redirect_to @question, notice: 'Question was successfully posted.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.html { redirect_to questions_url }
      format.json { head :ok }
    end
  end
  
  def rank_me
    if @current_user
      if params[:question_id]
        @question = Question.find(params[:question_id])
        @question = Rank.rank_me(@question,params,@current_user.id)
      end
      if params[:answer_id]
        @answer = Answer.find(params[:answer_id])
        @answer = Rank.rank_me(@answer,params,@current_user.id)
      end
    end
  end
  
  def update_new_answer
    @new_posts = Answer.fetch_new_posts(params[:after_last_posted])
    respond_to do |format|
      format.js
    end
  end


  private
  def load_basics
    @current_user = current_user
  end

  def check_if_owner
    @question ||= Question.find(params[:id])
    if current_user.try(:id) != @question.user_id
      respond_to do |format|
        format.html { redirect_to @question, notice: 'You cannot edit this question' }
        format.json { head :ok }
      end
    end
  end
  
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
        <% @question.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :header %><br />
    <%= f.text_field :header ,:style => ''%>
  </div>
  <div class="field">
    <%= f.label :question %><br />
    <%= f.text_area :question %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<script>
  $(document).ready(function() {
    window.setInterval(fetch_answers, 20000);
    function fetch_answers() {
      $.ajax({
        url: '/questions/update_new_answer', type: 'get',dataType:'script',data: { after_last_posted: $('#rescent-posts tbody tr:first td').attr('class')},
        success: function(){}
      });
      return false;
    }
  });
</script>
<div class="page-header index-header">
  <h1 style="float:left;">QnA Forum Questions</h1><%= link_to image_tag('rss.png') ,questions_url(:rss), :style=> 'float:right;'%>
</div>
  
<div style="float:left;">
  <div style="margin-bottom: 10px; float: right;">
    <%= link_to 'Ask Question', new_question_path ,:class=> 'btn'%>
  </div>

  <table style="width: 630px;">

    <h4>Top Questions</h4>

    <% @questions.each do |question| %>
      <tr>
        <td>
          <div class="question-summary">
            <div class="votes">
              <div class="mini-counts"><%= question.rank %></div>
              <div>votes</div>
            </div>
            <div class="status answered">
              <div class="mini-counts"><%= question.answers.count %></div>
              <div>answers</div>
            </div>
            <div class="summary">
              <%= raw link_to question.header, question %>
            </div>
            <div class="started-thread">
              Posted by: <small class="help-inline"><%= link_to user_name(question.user_id), :controller=>"contact", :action=>"index" ,:user_id => question.user_id %></small>
              <span class="reputation-score" title="karma <%= user_karma(question.user_id) %>"><%= user_karma(question.user_id) %></span>
            </div>
          </div>
        </td>
      </tr>
    <% end %>
  </table>
  <%= will_paginate @questions %>
</div>
<div class="right-feed-container">
  <div id="rescent-activity">
    <h4>Recent Activities</h4>
    <table id="rescent-posts">
      <% @rescent_answers.each do |ans| %>
        <tr>
          <td class=<%= ans.id %>>
            <b><%= raw link_to ans.question.header, ans.question ,:style => 'color:black'%></b><br/>
            <%= raw truncate(ans.answer, :length => 80, :omission => '...') %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/questions/new.html.erb
<h1>New question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/rank_me.js.erb
<% if @current_user %>
  <% if params[:question_id] %>
    $("#question_<%= params[:question_id]%>").html("<%= @question.rank %>");
  <% end %>

  <% if params[:answer_id]%>
    $("#answer_<%= params[:answer_id]%>").html("<%= @answer.rank %>");
  <% end %>
<% end %>

app/views/questions/show.html.erb
<% if notice %>
  <p id="notice" class="alert alert-success"><%= notice %></p>
<%end%>
<div class="page-header question-block">
  <div id="item-ranking">
    <ul class="ranking-block">
      <li><%= link_to image_tag('up.jpg'), {:controller => "questions", :action => "rank_me", :vote_up => true ,:question_id =>  @question.id },:title => 'This question shows research effort; it is useful and clear (click again to undo)',:class => 'vote-up-off',:remote => true %></li>
      <li id="question_<%= @question.id%>" class="rank-voted"><%= @question.rank %></li>
      <li><%= link_to image_tag('down.jpg'), {:controller => "questions", :action => "rank_me", :vote_down => true ,:question_id =>  @question.id },:title => 'This question does not show any research effort; it is unclear or not useful (click again to undo)',:class => 'vote-down-off',:remote => true %></li>
    </ul>    
  </div>
  <h2><%= raw @question.header %></h2>
  <p><%= raw @question.question %></p><br/>
  <div class="started-thread">
    Posted by: <small class="help-inline"><%= link_to user_name(@question.user_id), :controller=>"contact", :action=>"index" ,:user_id => @question.user_id %></small>
    <span class="reputation-score" title="karma <%= user_karma(@question.user_id) %>"><%= user_karma(@question.user_id) %></span>
  </div>
  <%= link_to 'Edit', edit_question_path(@question) %> |
  <%= link_to 'Back', questions_path %>
</div>

<table style="width:700px;">
  <h2> Answers</h2><br />
  <% @answers.each do |ans| %>

    <tr>
      <td>
        <div class="question-block answer-block">
          <div id="item-ranking">
            <ul class="ranking-block">
              <li><%= link_to image_tag('up.jpg'), {:controller => "questions", :action => "rank_me", :vote_up => true ,:answer_id =>  ans.id },:title => 'This answer shows research effort; it is useful and clear (click again to undo)',:class => 'vote-up-off',:remote => true %></li>
              <li id="answer_<%= ans.id %>"class="rank-voted"><%= ans.rank %></li>
              <li><%= link_to image_tag('down.jpg'), {:controller => "questions", :action => "rank_me", :vote_down => true ,:answer_id =>  ans.id },:title => 'This answer does not show any research effort; it is unclear or not useful (click again to undo)',:class => 'vote-up-off',:remote => true %></li>
            </ul>
          </div>

          <div style="float: right; width:555px;">
            <div class="answer-info">
              <%= h(ans.answer) %>
            </div>

            <div class="scaffold-links">
              <%= link_to 'Edit', edit_question_answer_path(@question,ans) %> |
              <%= link_to 'Destroy', [@question,ans], confirm: 'Are you sure?', method: :delete %>
            </div>

            <div class="started-thread">
              Posted by: <small class="help-inline"><%= link_to user_name(ans.user_id), :controller=>"contact", :action=>"index" ,:user_id => ans.user_id %></small>
              <span class="reputation-score" title="karma <%= user_karma(ans.user_id) %>"><%= user_karma(ans.user_id) %></span>
            </div>

            <div style="clear:both;"></div>
            <div class="error-notification supernovabg" style="display: block;visibility: hidden;">
              <h4>Please
                <a href="">login or register</a>
                to vote for this post.
              </h4>
              <span class="error-close">(click on this box to dismiss)</span>
            </div>
          </div>
        </div>
      </td>
    </tr>
  <%end%>

</table>
<br />
<br /><br />
<h2>Post new answer here</h2>
<%= form_for([@question,@answer],:html => {:class => 'well'}) do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
        <% @answer.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.label :answer ,:class => 'control-label',:style => 'padding-right:10px;'%>
  <%= f.text_area :answer ,{:class => 'input-xlarge',:rows => "7"} %>
  <div class="actions">
    <%= f.submit ("Post Answer")%>
  </div>
<% end %>

app/views/questions/update_new_answer.js.erb
<% if @new_posts.present? %>
  <%  @new_posts.each do |new_post|%>
    $('#rescent-posts tbody tr:first').before('<tr><td class="<%= new_post.id %>"><b><%= raw escape_javascript(link_to new_post.question.header,new_post.question,:style=>'color:black') %></b><br/><%= raw escape_javascript(truncate(new_post.answer,:length => 80, :omission => '...')) %></td></tr>');
  <%end%>
<%end%>